FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip

WORKDIR /app
# RUN python -m venv /app/.venv

COPY requirements.txt .
COPY main.py .

RUN python -m pip install -r requirements.txt

CMD uvicorn main:app --host 0.0.0.0
